-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.application_request;

CREATE TABLE IF NOT EXISTS public.application_request
(
    id text,
    pan_id text,
    phone_id text,
    email_id text,
    version integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.application_journey;

CREATE TABLE IF NOT EXISTS public.application_journey
(
    application_id text,
    journey_id text
);

DROP TABLE IF EXISTS public.journey;

CREATE TABLE IF NOT EXISTS public.journey
(
    id text,
    stage_name text NOT NULL,
    stage_sequence integer NOT NULL,
    journey_name text,
    end_point_key text,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.pan_step_details;

CREATE TABLE IF NOT EXISTS public.pan_step_details
(
    pan_id text,
    application_id text NOT NULL,
    version integer,
    address text,
    score text,
    PRIMARY KEY (pan_id, application_id)
);

DROP TABLE IF EXISTS public.phone_step_details;

CREATE TABLE IF NOT EXISTS public.phone_step_details
(
    phone_id text,
    application_id text NOT NULL,
    phone_details text,
    score integer,
    version integer,
    PRIMARY KEY (phone_id, application_id)
);

DROP TABLE IF EXISTS public.email_step_details;

CREATE TABLE IF NOT EXISTS public.email_step_details
(
    email_id integer,
    application_id text NOT NULL,
    email_details text,
    version integer,
    PRIMARY KEY (email_id, application_id)
);

ALTER TABLE IF EXISTS public.application_journey
    ADD CONSTRAINT fkey_journey FOREIGN KEY (journey_id)
    REFERENCES public.journey (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.application_journey
    ADD CONSTRAINT fkey_app FOREIGN KEY (application_id)
    REFERENCES public.application_request (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pan_step_details
    ADD CONSTRAINT fkey_app FOREIGN KEY (application_id)
    REFERENCES public.application_request (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.phone_step_details
    ADD CONSTRAINT fkey_app FOREIGN KEY (application_id)
    REFERENCES public.application_request (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.email_step_details
    ADD CONSTRAINT fkey_app FOREIGN KEY (application_id)
    REFERENCES public.application_request (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
